### ISSUE TITLE
Can styleguide style load via link tag instead of style tag?

### ISSUE THREAD

**Issue by miusuncle** [vue-microfrontends/styleguide#20]
Is it possible to use `css-minimizer-webpack-plugin` instead of `style-loader` in production?

**Comment by joeldenning** [comment]
Yes, you can use [single-spa-css](https://github.com/single-spa/single-spa-css) to load css files that are in separate files. I'd like to switch over create-single-spa and vue-cli-plugin-single-spa over to use it rather than style-loader in production, but haven't done so yet. You can still do so though for your projects by modifying the webpack config to use https://webpack.js.org/plugins/mini-css-extract-plugin/ rather than style-loader.

**Comment by miusuncle** [comment]
`single-spa-css` is meant to use for single-spa app or parcel. But styleguide is of type utilities and it doesn't have any sense to expose lifecycle methods(bootstrap, mount, unmount). So  my question is: how to use `single-spa-css` with styleguide utilities?

**Comment by joeldenning** [comment]
One option for utility modules is to use [css browser modules](https://github.com/systemjs/systemjs/blob/main/docs/module-types.md#css-modules), which are supported by systemjs. The css file would be a runtime static dependency of the systemjs bundle (a webpack external) and then the utility module can add it to the adopted stylesheets. I don't usually broadcast it as a solution because it requires some additional polyfilling for IE11 and the spec for CSS modules wasn't as far along in the standardization process as it is now. But that way would work well
