### ISSUE TITLE
Example with vue 3

### ISSUE THREAD

**Issue by drexlerux** [vue-microfrontends/styleguide#8]
I did this example with vue 3 and TS, but I have the following Errors, I appreciate your help.

![image](https://user-images.githubusercontent.com/29631825/102777881-80fdc180-435f-11eb-9918-5e57581e2853.png)

Dependencies: vue-loader: 16.xxx

Webpack Config:
![image](https://user-images.githubusercontent.com/29631825/102778207-2a44b780-4360-11eb-83a3-50065b1fd033.png)

**Comment by joeldenning** [comment]
I might upgrade this example to Vue 3 at some point. Loading Vue 3 with SystemJS has been tricky because Vue 3 no longer publishes a UMD bundle. However, we've got it figured out now. See https://github.com/musashiM82/root-config, https://github.com/musashiM82/app1, https://github.com/musashiM82/app2, etc which is an example maintained by @musashiM82.

Also see https://github.com/systemjs/systemjs/issues/2272 where loading Vue 3 with systemjs was discussed at length.

Specifically the `System.set()` approach is the best, since there are no race conditions. See https://github.com/systemjs/systemjs/issues/2272#issuecomment-744636282

**Comment by drexlerux** [comment]
Thank you very much, it was a great help
